# https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose/blob/master/2-containers/compose-v3/labels/docker-compose.yaml

version: '3'

services:

  bitcoin:
    command: 1000:1000 bitcoind
    image: cyphernode/bitcoin:v0.17.1
    volumes:
      - "$HOME/data/bitcoin:/.bitcoin"
    restart: always
    networks:
      - electrsnet

# docker run --rm -it \
#       -v conf:/etc/nginx/conf.d \
#       -v vhost:/etc/nginx/vhost.d \
#       -v html:/usr/share/nginx/html \
#       -v dhparam:/etc/nginx/dhparam \
#       -v certs:/etc/nginx/certs:ro \
#       -v /var/run/docker.sock:/tmp/docker.sock:ro \
#       -v $PWD/nginx/nginx.conf:/app/nginx-tcp.conf \
#       -v $PWD/nginx/bootstrap.sh:/app/bootstrap.sh \
#       -l com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
#       --network=electrsnet \
#       -p 80:80 -p 443:443 -p 50002:50002 \
#       jwilder/nginx-proxy ./bootstrap.sh bash

  nginx-proxy:
    image: jwilder/nginx-proxy
    command: ./bootstrap.sh
    ports:
      - "80:80"
      - "443:443"
      - "50002:50002"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $PWD/nginx/nginx.conf:/app/nginx-tcp.conf
      - $PWD/nginx/bootstrap.sh:/app/bootstrap.sh
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    networks:
      - electrsnet

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - electrsnet

  electrs:
    image: electrs-app:latest
    command: electrs -vvvv --timestamp --db-dir /home/user/db --daemon-rpc-addr=bitcoin:8332 --electrum-rpc-addr=0.0.0.0:50001
    depends_on:
      - letsencrypt
    env_file:
      - electrs.env
    volumes:
      - "$HOME/data/bitcoin:/home/user/.bitcoin:ro"
      - "$HOME/data/electrs:/home/user"
    restart: always
    networks:
      - electrsnet

  tor:
    image: tor:latest
    command: tor -f /home/tor/tor/torrc
    depends_on:
      - electrs
    volumes:
      - "$HOME/data/tor:/home/tor/tor"
    restart: always
    networks:
      - electrsnet

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:

networks:
  electrsnet:
    external: true
