version: '2.1'

services:

  bitcoin:
    command: 1000:1000 bitcoind
    image: cyphernode/bitcoin:v0.17.1
    volumes:
      - "$HOME/data/bitcoin:/.bitcoin"
    restart: always
    networks:
      - electrsnet

  electrs:
    image: electrs-app:latest
    command: electrs -vvvv --timestamp --db-dir /home/user/db --daemon-rpc-addr=bitcoin:8332 --electrum-rpc-addr=0.0.0.0:50001
    volumes:
      - "$HOME/data/bitcoin:/home/user/.bitcoin:ro"
      - "$HOME/data/electrs:/home/user"
    expose:
      - "50001"
    labels:
      - "traefik.docker.network=electrsnet"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:electrum.kexkey.com"
      - "traefik.basic.port=50001"
      - "traefik.basic.protocol=http"
    restart: always
    networks:
      - electrsnet

networks:
  electrsnet:
    external: true
